# Generated by Django 4.0.1 on 2022-02-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cryptotable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ranking', models.IntegerField(verbose_name='Rank')),
                ('Crypto_Name', models.CharField(max_length=255, verbose_name='Crypto Name')),
                ('Price', models.IntegerField(verbose_name='Price')),
                ('Change_24_H', models.IntegerField(verbose_name='Changes 24H')),
                ('Change_7_D', models.IntegerField(verbose_name='Changes 7D')),
                ('Change_30_D', models.IntegerField(verbose_name='Changes 30D')),
                ('Change_1_Y', models.IntegerField(verbose_name='Changes 1Y')),
                ('Marketcap', models.CharField(max_length=255, verbose_name='Market Cap')),
                ('Volume', models.CharField(max_length=255, verbose_name='Volume 24H')),
                ('Supply', models.CharField(max_length=255, verbose_name='Available Supply')),
            ],
        ),
    ]
