# Generated by Django 4.0.1 on 2022-02-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptotable',
            name='Ranking',
        ),
    ]
