# Generated by Django 4.0.1 on 2022-02-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_remove_cryptotable_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptotable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
