# Generated by Django 4.0.1 on 2022-02-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_cryptotable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptotable',
            name='Change_1_Y',
            field=models.CharField(max_length=255, verbose_name='Changes 1Y'),
        ),
        migrations.AlterField(
            model_name='cryptotable',
            name='Change_24_H',
            field=models.CharField(max_length=255, verbose_name='Changes 24H'),
        ),
        migrations.AlterField(
            model_name='cryptotable',
            name='Change_30_D',
            field=models.CharField(max_length=255, verbose_name='Changes 30D'),
        ),
        migrations.AlterField(
            model_name='cryptotable',
            name='Change_7_D',
            field=models.CharField(max_length=255, verbose_name='Changes 7D'),
        ),
        migrations.AlterField(
            model_name='cryptotable',
            name='Price',
            field=models.CharField(max_length=255, verbose_name='Price'),
        ),
    ]
