# Generated by Django 4.0.1 on 2022-02-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_alter_cryptotable_change_1_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testtable',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('t_Crypto_Name', models.CharField(max_length=255, verbose_name='Crypto Name')),
                ('t_Price', models.CharField(max_length=255, verbose_name='Price')),
                ('t_Change_24_H', models.CharField(max_length=255, verbose_name='Changes 24H')),
                ('t_Change_7_D', models.CharField(max_length=255, verbose_name='Changes 7D')),
                ('t_Change_30_D', models.CharField(max_length=255, verbose_name='Changes 30D')),
                ('t_Change_1_Y', models.CharField(max_length=255, verbose_name='Changes 1Y')),
                ('t_Marketcap', models.CharField(max_length=255, verbose_name='Market Cap')),
                ('t_Volume', models.CharField(max_length=255, verbose_name='Volume 24H')),
                ('t_Supply', models.CharField(max_length=255, verbose_name='Available Supply')),
            ],
        ),
    ]
