# Generated by Django 4.0.1 on 2022-02-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_testtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='t_Change_1_Y',
            field=models.IntegerField(verbose_name='Changes 1Y'),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='t_Change_24_H',
            field=models.IntegerField(verbose_name='Changes 24H'),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='t_Change_30_D',
            field=models.IntegerField(verbose_name='Changes 30D'),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='t_Change_7_D',
            field=models.IntegerField(verbose_name='Changes 7D'),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='t_Marketcap',
            field=models.IntegerField(verbose_name='Market Cap'),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='t_Price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='t_Volume',
            field=models.IntegerField(verbose_name='Volume 24H'),
        ),
    ]
