# Generated by Django 4.0.1 on 2022-02-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_alter_testtable_t_change_1_y_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testtable',
        ),
    ]
