# Generated by Django 4.0.1 on 2022-02-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_predicttable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='predicttable',
        ),
    ]
